

export const Layer1List = [ 
  { id: 'bitcoin', name: 'Bitcoin' }, 
  { id: 'ethereum', name: 'Ethereum' },
  { id: 'cardano', name: 'Cardano' },
  { id: 'solana', name: 'Solana' },
  { id: 'binancecoin', name: 'BNB' },
  { id: 'avalanche2', name: 'Avalanche' },
  { id: "polkadot", name: "Polkadot" },
  { id: "cosmos", name: "Cosmos Hub" }, // official CoinGecko name
  { id: "algorand", name: "Algorand" },
  { id: "near", name: "NEAR Protocol" },
  { id: "hedera-hashgraph", name: "Hedera" },
  { id: "tezos", name: "Tezos" },
  { id: "elrond-erd-2", name: "MultiversX" }, // rebranded from Elrond
  { id: "harmony", name: "Harmony" },
  { id: "flow", name: "Flow" },
  { id: "internet-computer", name: "Internet Computer" },
  { id: "tron", name: "TRON" },
  { id: "kadena", name: "Kadena" },
  { id: "ripple", name: "XRP" }, // id is ripple, but name is XRP
  { id: "zilliqa", name: "Zilliqa" }
];
  

export const Layer2List = [
  { id: "matic-network", name: "Polygon" },
  { id: "arbitrum", name: "Arbitrum" },
  { id: "optimism", name: "Optimism" },
  { id: "immutable-x", name: "Immutable X" },
  { id: "loopring", name: "Loopring" },
  { id: "starknet", name: "StarkNet" },
  { id: "zksync", name: "zkSync" },
  { id: "boba-network", name: "Boba Network" },
  { id: "metis-token", name: "MetisDAO" },
  { id: "cartesi", name: "Cartesi" },
  { id: "omisego", name: "OMG Network" },
  { id: "hermez-network", name: "Hermez" },
  { id: "celer-network", name: "Celer Network" },
  { id: "mantle", name: "Mantle" },
  { id: "scroll", name: "Scroll" },
  { id: "linea", name: "Linea" } 
];

export const DeFiTokensList = [
  { id: "uniswap", name: "Uniswap" },
  { id: "aave", name: "Aave" },
  { id: "maker", name: "Maker" },
  { id: "compound-governance-token", name: "Compound" },
  { id: "curve-dao-token", name: "Curve" },
  { id: "sushi", name: "SushiSwap" },
  { id: "balancer", name: "Balancer" },
  { id: "yearn-finance", name: "Yearn Finance" },
  { id: "dydx", name: "dYdX" },
  { id: "pancakeswap-token", name: "PancakeSwap" },
  { id: "gmx", name: "GMX" },
  { id: "thorchain", name: "THORChain" },
  { id: "kava", name: "Kava" },
  { id: "venus", name: "Venus" },
  { id: "instadapp", name: "InstaDapp" },
  { id: "harvest-finance", name: "Harvest Finance" },
  { id: "liquity", name: "Liquity" },
  { id: "staked-ether", name: "Staked Ether" },
  { id: "wrapped-steth", name: "Wrapped stETH" },
  { id: "maple", name: "Maple Finance" }
];

export const StableCoins = [
  "tether", "usd coin", "binance usd", "dai", "trueusd",
  "pax dollar", "gemini dollar", "frax", "terraclassicusd", "susd",
  "fei usd", "reserve rights", "husd", "eurs", "alchemix usd",
  "celo dollar", "liquity usd", "usdcoin", "uxd protocol", "usdj"
];

export const MemeCoins = [
  "dogecoin", "shiba inu", "pepe", "floki inu", "baby doge coin",
  "dogebonk", "dogelon mars", "samoyedcoin", "pitbull", "catecoin",
  "hoge finance", "kishu inu", "monacoin", "akita inu", "banano",
  "woofy", "shiba predator", "volt inu", "saitama"
];


export const COIN_DESC_SHORT = Object.freeze({
  // Layer 1

  bitcoin: "The first cryptocurrency and digital gold.",
  ethereum: "Smart contract network for apps and DeFi.",
  cardano: "Proof-of-stake blockchain for scalability.",
  solana: "Fast blockchain with low fees.",
  avalanche2: "Avalanche is a fast, scalable blockchain.",
  polkadot: "Network connecting multiple blockchains.",
  cosmos: "Framework for interoperable blockchains.",
  algorand: "Eco-friendly chain for payments and DeFi.",
  near_protocol: "Scalable, developer-friendly blockchain.",
  hedera: "Hashgraph ledger for fast apps.",
  tezos: "Smart contract chain that upgrades itself.",
  elrond: "Sharded chain for speed and scale.",
  harmony: "Cross-chain sharded blockchain.",
  flow: "Chain for NFTs and games.",
  internet_computer: "Blockchain aiming to replace cloud servers.",
  fantom: "Low-cost chain popular for DeFi.",
  tron: "Chain for apps, tokens, and media.",
  kadena: "Enterprise blockchain with hybrid design.",
  zilliqa: "Sharded blockchain for high throughput.",
  binancecoin: "BNB Chain for DeFi and exchange apps.",
  ripple: "Ledger for cheap, fast payments.",

  // Layer 2
  polygon: "Ethereum sidechain for low-cost txns.",
  arbitrum: "Ethereum rollup for speed and cost.",
  optimism: "Layer 2 rollup scaling Ethereum.",
  immutable_x: "NFT trading with no gas fees.",
  loopring: "DEX using zk-rollups.",
  starknet: "Secure zk-rollup for Ethereum.",
  zksync: "Fast zk-rollup payments on Ethereum.",
  boba_network: "Rollup with hybrid compute.",
  metisdao: "Layer 2 for DAOs and apps.",
  cartesi: "Linux-based Layer 2 contracts.",
  omg_network: "Plasma chain for Ethereum scaling.",
  fuel: "Execution layer for rollups.",
  aztec: "Privacy zk-rollup for Ethereum.",
  hermez: "zk-rollup scaling Ethereum.",
  celer_network: "Cross-chain scaling platform.",
  mantle: "Modular Layer 2 on Ethereum.",
  shardeum: "EVM chain with sharding.",
  scroll: "zk-rollup scaling Ethereum.",
  linea: "zkEVM Layer 2 by Consensys.",

  // DeFi Tokens
  uniswap: "Leading DEX for token swaps.",
  aave: "DeFi protocol for lending and borrowing.",
  maker: "DAO behind the DAI stablecoin.",
  compound: "Lending and interest via contracts.",
  curve: "DEX for stablecoin swaps.",
  sushiswap: "Community-run DEX forked from Uniswap.",
  balancer: "DEX with multi-asset pools.",
  yearn_finance: "Automates DeFi yield strategies.",
  dydx: "DEX for derivatives and futures.",
  pancakeswap: "Main DEX on BNB Chain.",
  gmx: "Perpetual trading DEX.",
  thorchain: "Cross-chain swaps of native assets.",
  kava: "DeFi lending and stablecoin platform.",
  venus: "Money markets on BNB Chain.",
  instadapp: "Smart wallet for DeFi apps.",
  harvest_finance: "Auto-compounding yield farming.",
  liquity: "ETH-backed loans with 0% interest.",
  maple_finance: "On-chain credit for institutions.",
  stakedether: "Tokenized staked ETH by Lido.",
  wrappedsteth: "Wrapped stETH for DeFi apps.",

  // Stablecoins
  tether: "Most used USD-pegged stablecoin.",
  usdcoin: "USD-backed stablecoin by Circle.",
  binance_usd: "USD-pegged stablecoin by Binance.",
  dai: "Decentralized USD stablecoin by Maker.",
  trueusd: "Regulated USD-backed stablecoin.",
  pax_dollar: "USD stablecoin issued by Paxos.",
  gemini_dollar: "USD stablecoin from Gemini.",
  frax: "Hybrid algorithmic stablecoin.",
  terraclassicusd: "Collapsed Terra USD token.",
  susd: "Synthetic USD by Synthetix.",
  fei_usd: "Algorithmic USD stablecoin.",
  reserve_rights: "Governance token for RSR.",
  husd: "Stablecoin once backed by Huobi.",
  eurs: "Euro-backed stablecoin.",
  alchemix_usd: "Self-repaying stablecoin.",
  celo_dollar: "Stablecoin on Celo network.",
  liquity_usd: "Stablecoin from Liquity loans.",
  uxd_protocol: "Delta-neutral stablecoin.",
  usdj: "Stablecoin backed on Tron.",

  // Meme Coins
  dogecoin: "The first meme coin, inspired by Doge.",
  shiba_inu: "Dogecoin-style token on Ethereum.",
  pepe: "Meme token from Pepe the Frog.",
  floki_inu: "Coin named after Musk’s dog.",
  baby_doge_coin: "Dogecoin spinoff with community.",
  dogebonk: "Humor-driven meme coin.",
  dogelon_mars: "Space-themed Dogecoin spinoff.",
  samoyedcoin: "Dog meme coin on Solana.",
  pitbull: "Community meme coin with staking.",
  catecoin: "Meme coin for creators.",
  hoge_finance: "Deflationary meme coin with burns.",
  kishu_inu: "Dog meme coin on Ethereum.",
  monacoin: "First Japanese meme coin.",
  akita_inu: "Dogecoin-style meme rival.",
  banano: "Feeless meme coin from Nano.",
  woofy: "Companion token to YFI.",
  shiba_predator: "Rival token to Shiba Inu.",
  volt_inu: "Deflationary meme coin.",
  saitama: "Meme coin for education."
});

export const COIN_DESC_LONG = Object.freeze({
  // Layer 1
  bitcoin: "The first cryptocurrency, often called digital gold, known for its security, scarcity, and role as a store of value.",
  ethereum: "The leading smart contract platform powering DeFi, NFTs, and decentralized applications worldwide.",
  cardano: "A proof-of-stake blockchain focused on scalability, sustainability, and research-driven development.",
  solana: "A high-speed blockchain offering ultra-low fees, popular for DeFi and NFT ecosystems.",
  avalanche2: "A highly scalable blockchain with fast finality and support for custom subnets and DeFi applications.",
  polkadot: "An ecosystem connecting multiple blockchains with interoperability through parachains.",
  cosmos: "The ‘Internet of Blockchains,’ enabling cross-chain communication and modular development.",
  algorand: "An eco-friendly, fast blockchain optimized for payments, DeFi, and enterprise use cases.",
  near_protocol: "A developer-friendly chain with sharding for scalability and user-friendly onboarding.",
  hedera: "A fast, secure distributed ledger using hashgraph consensus, often used for enterprise apps.",
  tezos: "A self-amending smart contract blockchain with strong governance and upgradeability.",
  elrond: "A sharded blockchain delivering high throughput, rebranded as MultiversX for the metaverse.",
  harmony: "A cross-chain sharded protocol with fast finality for dApps and DeFi.",
  flow: "A blockchain built for NFTs, games, and large-scale consumer applications.",
  internet_computer: "A decentralized computing platform aiming to replace traditional cloud infrastructure.",
  fantom: "An EVM-compatible chain with low fees and fast finality, popular in DeFi.",
  tron: "A blockchain for content sharing, DeFi, and tokens, with high throughput and low fees.",
  kadena: "A hybrid blockchain combining public and private networks with scalable smart contracts.",
  zilliqa: "A pioneer in sharding, enabling high transaction throughput for DeFi and gaming.",
  binancecoin: "BNB Chain’s native token powering DeFi, trading, and Binance ecosystem apps.",
  ripple: "XRP Ledger enabling fast, low-cost cross-border payments for financial institutions.",

  // Layer 2
  polygon: "Ethereum’s leading sidechain offering low-cost transactions and broad dApp adoption.",
  arbitrum: "A popular Ethereum Layer 2 rollup solution providing scalability and low gas fees.",
  optimism: "An optimistic rollup for Ethereum scaling, known for its speed and developer support.",
  immutable_x: "Layer 2 for NFTs on Ethereum with instant trading and zero gas fees.",
  loopring: "A zk-rollup based DEX protocol delivering fast and low-cost Ethereum trades.",
  starknet: "A general-purpose zk-rollup for Ethereum scaling, developed by StarkWare.",
  zksync: "A zk-rollup enabling fast, cheap payments and Ethereum transactions.",
  boba_network: "An L2 rollup with hybrid compute, bridging on- and off-chain resources.",
  metisdao: "A Layer 2 rollup optimized for DAOs, dApps, and scalability.",
  cartesi: "Layer 2 enabling Linux-based smart contracts and off-chain computation.",
  omg_network: "An early Ethereum scaling Plasma chain designed for cheaper transactions.",
  fuel: "An execution layer optimized for modular rollup scalability.",
  aztec: "A privacy-first zk-rollup for Ethereum enabling shielded transactions.",
  hermez: "zk-rollup technology scaling Ethereum, now part of Polygon zkEVM.",
  celer_network: "Cross-chain scaling platform powering bridges, L2, and interop solutions.",
  mantle: "A modular Ethereum Layer 2 chain focused on high performance.",
  shardeum: "An EVM-based sharded blockchain for infinite scalability.",
  scroll: "A zk-rollup Layer 2 focused on Ethereum compatibility.",
  linea: "A zkEVM Layer 2 by ConsenSys bringing scalability to Ethereum.",

  // DeFi Tokens
  uniswap: "The leading decentralized exchange protocol enabling peer-to-peer token swaps.",
  aave: "A major DeFi lending platform for borrowing, lending, and earning interest.",
  maker: "The DAO governing DAI, a decentralized stablecoin backed by collateral.",
  compound: "An algorithmic money market protocol for lending and borrowing assets.",
  curve: "A DEX optimized for efficient stablecoin swaps with low slippage.",
  sushiswap: "A community-driven DEX and DeFi ecosystem forked from Uniswap.",
  balancer: "A multi-asset automated market maker and portfolio manager.",
  yearn_finance: "DeFi protocol automating yield farming and optimizing returns.",
  dydx: "A decentralized exchange for margin, derivatives, and perpetuals trading.",
  pancakeswap: "BNB Chain’s biggest DEX with token swaps, farms, and lotteries.",
  gmx: "A decentralized perpetuals trading exchange with zero price impact swaps.",
  thorchain: "A cross-chain DEX enabling native asset swaps without wrapped tokens.",
  kava: "A cross-chain DeFi platform offering stablecoins and lending.",
  venus: "A money market protocol on BNB Chain for lending and borrowing.",
  instadapp: "A smart DeFi wallet that simplifies managing assets across protocols.",
  harvest_finance: "A yield optimizer automating yield farming strategies.",
  liquity: "A borrowing protocol offering ETH-backed loans with 0% interest.",
  maple_finance: "An on-chain institutional lending marketplace.",
  stakedether: "Lido’s liquid staking token representing staked ETH.",
  wrappedsteth: "Wrapped version of stETH for broader DeFi compatibility.",

  // Stablecoins
  tether: "The largest USD-pegged stablecoin, widely used in trading and payments.",
  usdcoin: "A regulated USD-backed stablecoin issued by Circle, used globally.",
  binance_usd: "A USD-pegged stablecoin from Binance and Paxos (phased out).",
  dai: "A decentralized stablecoin soft-pegged to the USD, backed by collateral.",
  trueusd: "A regulated, independently audited USD-backed stablecoin.",
  pax_dollar: "A stablecoin issued by Paxos, fully backed by USD reserves.",
  gemini_dollar: "A regulated USD stablecoin launched by Gemini exchange.",
  frax: "A fractional-algorithmic stablecoin with partial collateral backing.",
  terraclassicusd: "The failed TerraUSD stablecoin that lost its peg in 2022.",
  susd: "A synthetic USD stablecoin issued by Synthetix.",
  fei_usd: "An algorithmic stablecoin with direct incentives for price stability.",
  reserve_rights: "Governance token backing the Reserve stablecoin ecosystem.",
  husd: "Once a Huobi-backed USD stablecoin, now largely defunct.",
  eurs: "A euro-backed stablecoin for cross-border payments.",
  alchemix_usd: "A self-repaying stablecoin using future yield as repayment.",
  celo_dollar: "A stablecoin on the Celo network for mobile-first payments.",
  liquity_usd: "Stablecoin minted through Liquity’s ETH-backed loans.",
  uxd_protocol: "A delta-neutral stablecoin backed by derivatives.",
  usdj: "A Tron-based USD-pegged stablecoin issued on JustLend.",

  // Meme Coins
  dogecoin: "The original meme coin inspired by Doge the Shiba Inu, with a strong community.",
  shiba_inu: "Ethereum-based meme token turned DeFi ecosystem, dubbed the Dogecoin killer.",
  pepe: "A meme coin themed after Pepe the Frog, known for viral growth.",
  floki_inu: "A community token named after Elon Musk’s Shiba Inu dog.",
  baby_doge_coin: "A Dogecoin-inspired token with deflationary mechanics and charity focus.",
  dogebonk: "A humor-driven meme cryptocurrency with a satirical edge.",
  dogelon_mars: "A Doge-inspired meme token themed around space and Mars colonization.",
  samoyedcoin: "A Solana-based meme coin featuring the Samoyed dog breed.",
  pitbull: "A community-driven meme coin with staking and long-term burn mechanics.",
  catecoin: "A meme coin designed for creators, tipping, and play-to-earn.",
  hoge_finance: "A deflationary meme coin with auto-burns and community focus.",
  kishu_inu: "A Dogecoin-style meme coin with strong grassroots marketing.",
  monacoin: "Japan’s first meme coin with a dedicated domestic community.",
  akita_inu: "Another Dogecoin-inspired rival token, community-driven.",
  banano: "A feeless meme coin forked from Nano, themed around bananas.",
  woofy: "A companion meme token to Yearn Finance’s YFI.",
  shiba_predator: "A token branding itself as the rival to Shiba Inu.",
  volt_inu: "A deflationary meme coin with aggressive community marketing.",
  saitama: "A meme token promoting crypto education and community growth."
});
